# Generated by Django 3.2.4 on 2022-07-31 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0007_movie_saves'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_shares',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='movie_share_liked',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('yt', models.DateTimeField(auto_now_add=True)),
                ('movie_share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_share_liked', to='movie.movie_shares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_share_liked_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
