# Generated by Django 3.2.4 on 2022-06-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_books_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='img_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
