# Generated by Django 3.2.4 on 2022-07-14 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0003_alter_books_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='shares',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('comment', models.CharField(max_length=2000)),
                ('yt', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_share', to='book.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_share', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
