# Generated by Django 3.2.4 on 2022-07-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='hide',
            field=models.IntegerField(choices=[(0, 'herkes'), (1, 'gizli')], default=0),
        ),
    ]
