# Generated by Django 3.2.4 on 2022-07-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_shares_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='photo',
            field=models.ImageField(default='', upload_to='book/shares'),
            preserve_default=False,
        ),
    ]
