# Generated by Django 3.2.4 on 2022-07-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_shares_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='rate',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
    ]
