# Generated by Django 3.2.4 on 2022-07-14 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0007_shares_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_shares',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('photo', models.ImageField(upload_to='book/shares')),
                ('comment', models.CharField(max_length=2000)),
                ('yt', models.DateTimeField(auto_now_add=True)),
                ('hide', models.IntegerField(choices=[(0, 'herkes'), (1, 'gizli')], default=0)),
                ('rate', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_share', to='book.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='shares',
        ),
    ]
