# Generated by Django 3.2.4 on 2022-07-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_book_list_book_list_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_list',
            name='yt',
            field=models.DateTimeField(auto_now_add=True, default='2022-07-13 11:26'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_list_content',
            name='yt',
            field=models.DateTimeField(auto_now_add=True, default='2022-07-13 11:26'),
            preserve_default=False,
        ),
    ]
