# Generated by Django 3.2.4 on 2022-07-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20220719_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_list',
            name='hide',
            field=models.IntegerField(choices=[(0, 'herkes'), (1, 'gizli')], default=0),
        ),
    ]
