# Generated by Django 3.2.4 on 2022-07-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_book_list_hide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_shares',
            name='photo',
        ),
    ]
