# Generated by Django 3.2.4 on 2022-07-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_book_saves'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_shares',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
