# Generated by Django 3.2.4 on 2022-07-14 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='series_shares',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('photo', models.ImageField(upload_to='series/shares')),
                ('comment', models.CharField(max_length=2000)),
                ('yt', models.DateTimeField(auto_now_add=True)),
                ('hide', models.IntegerField(choices=[(0, 'herkes'), (1, 'gizli')], default=0)),
                ('rate', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_share', to='series.seriess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
