# Generated by Django 3.2.4 on 2022-07-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_series_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series_shares',
            name='photo',
            field=models.ImageField(null=True, upload_to='series/shares'),
        ),
    ]
