# Generated by Django 3.2.4 on 2022-07-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_series_list_series_list_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='series_list',
            name='hide',
            field=models.IntegerField(choices=[(0, 'herkes'), (1, 'gizli')], default=0),
        ),
    ]
