# Generated by Django 3.2.4 on 2022-08-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0008_auto_20220731_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series_shares',
            name='rate',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
    ]
