# Generated by Django 3.2.4 on 2022-08-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_photo',
            name='pp',
            field=models.ImageField(unique=True, upload_to='profile_photos'),
        ),
    ]
