# Generated by Django 3.2.4 on 2022-08-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_photo_pp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_photo',
            name='pp',
            field=models.ImageField(default='fakepp.jpg', unique=True, upload_to='profile_photos'),
        ),
    ]
